# 📘Домашнє завдання №13 Bagging

Виконав: **Bohdan Pinchuk**

Link: https://github.com/BogdanPinchuk/DataScience-PBY_HW13

## 📌 Завдання 1  
Використайте датасет Titanic:  
https://www.kaggle.com/datasets/yasserh/titanic-dataset  

- Завантажте дані  
- Проведіть базовий аналіз (огляд колонок, типів, пропусків)  
- Обробіть пропущені значення  
- Закодуйте категоріальні змінні через OneHotEncoding (наприклад, `Sex`, `Embarked`)  

---

## 📌 Завдання 2  
Побудуйте модель класифікації:

- Натренуйте **`RandomForestClassifier`**  
- Зробіть прогноз на тестових даних  
- Обчисліть метрики:
  - accuracy  
  - precision  
  - recall  
  - F1-score  

👉 Проаналізуйте:
- чи є переобучення  
- які метрики найважливіші в цій задачі  

---

## 📌 Завдання 3  
Аналіз важливості ознак:

- Отримайте `feature_importances_`  
- Побудуйте графік важливості ознак  

👉 Проаналізуйте:
- які ознаки найважливіші  
- чи співпадає це з інтуїцією (наприклад, `Sex`, `Pclass`, `Age`)  

---

## 📌 Завдання 4  
Використайте датасет Fish Market:  
https://www.kaggle.com/datasets/vipullrathod/fish-market  

- Побудуйте модель **`RandomForestRegressor`**  
- Натренуйте модель для прогнозування (наприклад, `Weight`)  
- Обчисліть метрики:
  - MSE  
  - RMSE  
  - R²  

👉 Проаналізуйте якість моделі  

---

## 📌 Завдання 5  
Тюнінг Random Forest:

- Використайте **`GridSearchCV`** або **`RandomizedSearchCV`**  
- Підберіть гіперпараметри:
  - `n_estimators`  
  - `max_depth`  
  - `min_samples_leaf`  
  - `max_features`  

- Знайдіть найкращу модель  
- Порівняйте метрики з результатами з **Завдання 4**  

👉 Зробіть висновок:
- чи покращилась модель після тюнінгу  
- які параметри найбільше вплинули

In [1]:
# Synchronization with remote source

import shutil
from pathlib import Path

# Input data
git_project_url = "https://github.com/BogdanPinchuk/DataScience-PBY_HW13.git"
main_file_name = "Bohdan_Pinchuk_DS_HW13.ipynb"

# Solution

# upload all files
current_path = !pwd
current_path = current_path[0]
parent_path = !dirname "$current_path"
parent_path = parent_path[0]
temp_path = f"{parent_path}/temp"

# Clone data
!rm -rf "$temp_path"
!git clone "$git_project_url" "$temp_path"

source = Path(temp_path)
destination = Path(current_path)
exclude = {main_file_name, ".git", ".idea"}

for item in source.iterdir():
    if item.name in exclude:
        continue

    target = destination / item.name
    if item.is_dir():
        shutil.copytree(item, target, dirs_exist_ok=True)
    else:
        shutil.copy2(item, target)

# Clean temp folder
!rm -rf "$temp_path"

Cloning into '/Users/bohdanpinchuk/Documents/Data Science/Development/Data_Science/Practical_tasks/Homework_13/temp'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 42 (delta 10), reused 39 (delta 7), pack-reused 0 (from 0)
Receiving objects: 100% (42/42), 402.17 KiB | 2.58 MiB/s, done.
Resolving deltas: 100% (10/10), done.

In [2]:
## Downloading data

# !pip install kagglehub[pandas-datasets]
# !pip install ipywidgets
# !pip install --upgrade nbformat
# !pip install jinja2

import apps.main as mn

# Input data
db_file_name = "store_hw13.db"

# Solution
titanic_dataset = mn.download_and_extract_from_kagglehub("yasserh/titanic-dataset", "Titanic-Dataset.csv", db_file_name)
fish_market = mn.download_and_extract_from_kagglehub("vipullrathod/fish-market", "Fish.csv", db_file_name)

# Print result
# display(titanic_dataset, fish_market)

## ✅ Рішення 1
Використайте датасет Titanic:
- Завантажте дані
- Проведіть базовий аналіз (огляд колонок, типів, пропусків)
- Обробіть пропущені значення
- Закодуйте категоріальні змінні через OneHotEncoding (наприклад, `Sex`, `Embarked`)

In [3]:
# Data analysis

import numpy as np
import pandas as pd
import apps.reporter as rpt

# Input data
data_set = titanic_dataset
n_columns = data_set.columns.size
n_rows = data_set.index.size

# Solution
columns_df = pd.DataFrame(data_set.columns, columns=["Columns"])
types_df = pd.DataFrame(data_set.dtypes, columns=["Types"])

col_num_type = data_set.select_dtypes(include=np.number).columns
col_cat_type = data_set.select_dtypes(exclude=np.number).columns

empty_val_by_col = data_set.isnull().sum().to_frame(name='count')
is_empty_val = empty_val_by_col.values.sum() > 0

rp = rpt.Reporter()
rp.add_item("Кількість рядків", str(n_rows))
rp.add_item("Кількість об’єктів у датасеті", str(n_rows))
rp.add_item("Кількість стовпців", str(n_columns))
rp.add_item("Кількість числових ознак", str(col_num_type.size))
rp.add_item("Кількість категоріальних ознак", str(col_cat_type.size))
rp.add_item("Пропущені значення", 'є' if is_empty_val > 0 else 'немає')
rp.print_pd_report("Параметри таблиці до обробки")

if is_empty_val > 0:
    display(empty_val_by_col.style.set_caption("Кількість пропусків"))

# Print results
display(data_set)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
# Data cleaning and filling

import numpy as np
import pandas as pd
import apps.reporter as rpt

# Input data
ages_col_name = "Age"
fares_col_name = "Fare"
sibsp_col_name = "SibSp"
parch_col_name = "Parch"
family_col_name = "Family"
fill_col_list = ["Age", "Embarked"]
drop_col_list = ["PassengerId", "Name", "Ticket", "Cabin"]

# Solution
titanic_dataset.drop(columns=drop_col_list, inplace=True)

# Заповнення пропусків
for col_name in fill_col_list:
    most_often_value = titanic_dataset[col_name].mode()[0]
    titanic_dataset[col_name] = titanic_dataset[col_name].fillna(most_often_value)

# Корегування даних
titanic_dataset[ages_col_name] = titanic_dataset[ages_col_name].round().astype(int)
titanic_dataset[fares_col_name] = titanic_dataset[fares_col_name].round(2).astype(float)

# Заміна даних і очищення
titanic_dataset[family_col_name] = titanic_dataset.apply(
    lambda df_row: df_row[sibsp_col_name] + df_row[parch_col_name] + 1, axis=1)
titanic_dataset.drop(columns=[sibsp_col_name, parch_col_name], inplace=True)

data_set = titanic_dataset
n_columns = data_set.columns.size
n_rows = data_set.index.size

columns_df = pd.DataFrame(data_set.columns, columns=["Columns"])
types_df = pd.DataFrame(data_set.dtypes, columns=["Types"])

col_num_type = data_set.select_dtypes(include=np.number).columns
col_cat_type = data_set.select_dtypes(exclude=np.number).columns

empty_val_by_col = data_set.isnull().sum().to_frame(name='count')
is_empty_val = empty_val_by_col.values.sum() > 0

rp = rpt.Reporter()
rp.add_item("Кількість рядків", str(n_rows))
rp.add_item("Кількість об’єктів у датасеті", str(n_rows))
rp.add_item("Кількість стовпців", str(n_columns))
rp.add_item("Кількість числових ознак", str(col_num_type.size))
rp.add_item("Кількість категоріальних ознак", str(col_cat_type.size))
rp.add_item("Пропущені значення", 'є' if is_empty_val > 0 else 'немає')
rp.print_pd_report("Параметри таблиці після обробки")

if is_empty_val > 0:
    display(empty_val_by_col.style.set_caption("Кількість пропусків"))

# Print results
display(data_set)

     Survived  Pclass     Sex  Age   Fare Embarked  Family
0           0       3    male   22   7.25        S       2
1           1       1  female   38  71.28        C       2
2           1       3  female   26   7.92        S       1
3           1       1  female   35  53.10        S       2
4           0       3    male   35   8.05        S       1
..        ...     ...     ...  ...    ...      ...     ...
886         0       2    male   27  13.00        S       1
887         1       1  female   19  30.00        S       1
888         0       3  female   24  23.45        S       4
889         1       1    male   26  30.00        C       1
890         0       3    male   32   7.75        Q       1

[891 rows x 7 columns]

In [5]:
# Data preparation

import numpy as np
import pandas as pd
import apps.reporter as rpt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Input data
cat_col_list = ["Sex", "Embarked"]
pd.options.display.float_format = '{:g}'.format

# Solution
preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), cat_col_list),
], remainder="passthrough", verbose_feature_names_out=False)

transformed_data = preprocessor.fit_transform(titanic_dataset)
titanic_dataset = pd.DataFrame(transformed_data, columns=preprocessor.get_feature_names_out())

data_set = titanic_dataset
n_columns = data_set.columns.size
n_rows = data_set.index.size

columns_df = pd.DataFrame(data_set.columns, columns=["Columns"])
types_df = pd.DataFrame(data_set.dtypes, columns=["Types"])

col_num_type = data_set.select_dtypes(include=np.number).columns
col_cat_type = data_set.select_dtypes(exclude=np.number).columns

empty_val_by_col = data_set.isnull().sum().to_frame(name='count')
is_empty_val = empty_val_by_col.values.sum() > 0

rp = rpt.Reporter()
rp.add_item("Кількість рядків", str(n_rows))
rp.add_item("Кількість об’єктів у датасеті", str(n_rows))
rp.add_item("Кількість стовпців", str(n_columns))
rp.add_item("Кількість числових ознак", str(col_num_type.size))
rp.add_item("Кількість категоріальних ознак", str(col_cat_type.size))
rp.add_item("Пропущені значення", 'є' if is_empty_val > 0 else 'немає')
rp.print_pd_report("Параметри таблиці після кодування")

if is_empty_val > 0:
    display(empty_val_by_col.style.set_caption("Кількість пропусків"))

# Print results
display(columns_df.style.set_caption("Назви колонок").hide(axis='index'))
display(types_df.style.set_caption("Типи даних"))
display(data_set)

,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Survived,Pclass,Age,Fare,Family
0,0,1,0,0,1,0,3,22,7.25,2
1,1,0,1,0,0,1,1,38,71.28,2
2,1,0,0,0,1,1,3,26,7.92,1
3,1,0,0,0,1,1,1,35,53.1,2
4,0,1,0,0,1,0,3,35,8.05,1
...,...,...,...,...,...,...,...,...,...,...
886,0,1,0,0,1,0,2,27,13,1
887,1,0,0,0,1,1,1,19,30,1
888,1,0,0,0,1,0,3,24,23.45,4
889,0,1,1,0,0,1,1,26,30,1
890,0,1,0,1,0,0,3,32,7.75,1

## ✅ Рішення 2
Побудуйте модель класифікації:

- Натренуйте **`RandomForestClassifier`**
- Зробіть прогноз на тестових даних
- Обчисліть метрики:
  - accuracy
  - precision
  - recall
  - F1-score

👉 Проаналізуйте:
- чи є перенавчання
- які метрики найважливіші в цій задачі

In [6]:
import gc
import pandas as pd
from sklearn.model_selection import train_test_split

# Input data
target_value = "Survived"
test_ratio = 0.2
rng_seed = 42

# Solution
X_data = titanic_dataset.drop(columns=[target_value])
Y_data = titanic_dataset[target_value]

del titanic_dataset

X_train, X_test, Y_train, Y_test = train_test_split(X_data, Y_data, test_size=test_ratio,
                                                    stratify=Y_data, random_state=rng_seed, shuffle=True)

# Print results
display(pd.concat([
    Y_train.value_counts(),
    Y_train.value_counts(normalize=True)
], axis=1).style.format_index("{:g}").set_caption("Вибірка для навчання"))
display(pd.concat([
    Y_test.value_counts(),
    Y_test.value_counts(normalize=True)
], axis=1).style.format_index("{:g}").set_caption("Вибірка для тестування"))

# Clean
_ = gc.collect()

In [7]:
import joblib
import apps.main as mn
from pathlib import Path
from IPython.core.display import Markdown
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

# Input data
rng_seed = 42
load_model = True
model_file_name = "resources/titanic-dataset.model"

# Solution
file_path = Path(model_file_name)

# try to load model
if load_model and file_path.exists():
    model = joblib.load(model_file_name)
else:
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=None,
        random_state=rng_seed,
        n_jobs=-1
    )
    model.fit(X_train, Y_train)
    # save model
    joblib.dump(model, model_file_name)

Y_pred = model.predict(X_test)
Y_pred_orig = model.predict(X_train)

# Print results
display(Markdown("**Тренувальні дані:**"))
mn.calc_class_metrics(Y_test, Y_pred)
print(classification_report(Y_test, Y_pred))
display(Markdown("---"))
display(Markdown("**Тестові дані:**"))
mn.calc_class_metrics(Y_train, Y_pred_orig)
print(classification_report(Y_train, Y_pred_orig))

**Тренувальні дані:**

              precision    recall  f1-score   support

         0.0       0.82      0.89      0.86       110
         1.0       0.80      0.70      0.74        69

    accuracy                           0.82       179
   macro avg       0.81      0.79      0.80       179
weighted avg       0.81      0.82      0.81       179

---

**Тестові дані:**

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99       439
         1.0       0.99      0.96      0.98       273

    accuracy                           0.98       712
   macro avg       0.98      0.98      0.98       712
weighted avg       0.98      0.98      0.98       712

In [11]:
import joblib
import apps.main as mn
from pathlib import Path
from IPython.core.display import Markdown
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

# Input data
rng_seed = 42
load_model = True
model_file_name = "resources/titanic-dataset_d5.model"

# Solution
file_path = Path(model_file_name)

# try to load model
if load_model and file_path.exists():
    model = joblib.load(model_file_name)
else:
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=5,
        random_state=rng_seed,
        n_jobs=-1
    )
    model.fit(X_train, Y_train)
    # save model
    joblib.dump(model, model_file_name)

Y_pred = model.predict(X_test)
Y_pred_orig = model.predict(X_train)

# Print results
display(Markdown("**Тренувальні дані:**"))
mn.calc_class_metrics(Y_test, Y_pred)
print(classification_report(Y_test, Y_pred))
display(Markdown("---"))
display(Markdown("**Тестові дані:**"))
mn.calc_class_metrics(Y_train, Y_pred_orig)
print(classification_report(Y_train, Y_pred_orig))

**Тренувальні дані:**

              precision    recall  f1-score   support

         0.0       0.80      0.94      0.86       110
         1.0       0.86      0.62      0.72        69

    accuracy                           0.82       179
   macro avg       0.83      0.78      0.79       179
weighted avg       0.82      0.82      0.81       179

---

**Тестові дані:**

              precision    recall  f1-score   support

         0.0       0.84      0.94      0.89       439
         1.0       0.88      0.72      0.79       273

    accuracy                           0.85       712
   macro avg       0.86      0.83      0.84       712
weighted avg       0.85      0.85      0.85       712

Із документації для "Confusion Matrix":

Колонка 1 | Колонка 2
--- | ---
true negatives :math:`C_{0,0}` | false positives :math:`C_{0,1}`
false negatives :math:`C_{1,0}` | true positives :math:`C_{1,1}`

Матриця:

№1 | №2
--|--
TN | FP
FN | TP

* TN — фактично/реально 0, передбачено/вгадано 0; (Правильно вказана смерть)
* FP — фактично/реально 0, передбачено/вгадано 1; (Хибна надія на виживання)
* FN — фактично/реально 1, передбачено/вгадано 0; (Помилково вказана смерть)
* TP — фактично/реально 1, передбачено/вгадано 1; (Правильно сповіщено про те що вижив)

- Accuracy (Точність) `[(TP + TN)/(Total)]`: Загальний відсоток правильних відповідей.
- Precision (Влучність) `[TP/(TP + FP)]`: Наскільки ми можемо довіряти моделі, коли вона каже "вижив".
- Recall (Повнота) `[TP/(TP + FN)]`: Який відсоток усіх, хто вижив, ми реально знайшли.

Висновок. Для аналізу чи модель перенавчилася, проведено аналіз прогнозування на тренувальних даних. Тренувальні дані значно більші від тестових, що свідчить, що модель перенавчилася. Для оцінки моделі може бути найважливішою метрикою є балансом між Precision і Recall. При обмеженні глибини дерева до 5 помітно, що метрики майже однакові, а тобто можна вважати, що модель не перенавчилася.